Cotacoes.MVC/Models/ErrorViewModel.cs
using System;

namespace Cotacoes.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cotacoes.MVC/Areas/Moedas/Controllers/ConversaoController.cs
using Microsoft.AspNetCore.Mvc;
using Cotacoes.Model;

namespace Cotacoes.MVC.Areas.Moedas.Controllers
{
    [Area("Moedas")]
    public class ConversaoController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "Converções";
            ViewBag.Data = TempData["Data"];
            ViewBag.Valor = TempData["Valor"];

            return View("Index");
        }

        [HttpPost]
        public IActionResult ConverterParaDolar([FromForm]string Moeda, [FromForm]decimal Montante)
        {
            var result = ConversaoService.ConverterParaDolar(Montante, Moeda);

            TempData["Data"] = result.DataConsulta;
            TempData["Valor"] = result.ValorConvertido;

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult ConverterParaReal([FromForm]string Moeda, [FromForm]decimal Montante)
        {
            var result = ConversaoService.ConverterParaReais(Montante, Moeda);

            TempData["Data"] = result.DataConsulta;
            TempData["Valor"] = result.ValorConvertido;

            return RedirectToAction("Index");
        }
    }
}

Cotacoes.MVC/Areas/Moedas/Controllers/CotacaoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cotacoes.MVC.Areas.Moedas.Controllers
{
    [Area("Moedas")]
    public class CotacaoController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "Informações";
            return View();
        }
    }
}

Cotacoes.MVC/Areas/Moedas/Controllers/InformacoesController.cs
using Microsoft.AspNetCore.Mvc;
using Cotacoes.Model;
using System.Collections.Generic;


namespace Cotacoes.MVC.Areas.Moedas.Controllers
{
    [Area("Moedas")]
    public class InformacoesController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "Moedas";

            return View();
        }

        public IActionResult Sobre(int Id)
        {
            
            var _moeda = new Model.Moeda(Id);
            ViewBag.Moeda = _moeda;
            ViewData["Title"] = $"{_moeda.Sigla}";

            return View();
        }
    }
}

Cotacoes.MVC/Areas/PainelAdministrativo/Controllers/HomeController.cs
using Cotacoes.Model;
using Microsoft.AspNetCore.Mvc;

namespace Cotacoes.MVC.Areas.PainelAdministrativo.Controllers
{
    [Area("PainelAdministrativo")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "Início";
            ViewData["NomeUsuario"] = TempData["Nome"];

            return View();
        }
    }
}

Cotacoes.MVC/Areas/Usuarios/Controllers/AutenticacaoController.cs
using Microsoft.AspNetCore.Mvc;
using Cotacoes.Model;

namespace Cotacoes.MVC.Areas.Autenticacao.Controllers
{
    [Area("Usuarios")]
    public class AutenticacaoController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "Login";
            ViewBag.Error = false;
            return View();
        }

        [HttpPost]
        public IActionResult Index([FromForm]string Email, [FromForm]string Senha)
        {
            if (UsuarioService.Autenticar(Email, Senha))
            {
                TempData["Nome"] = UsuarioService.ObterNome(Email);
                return RedirectToAction("Index", "Home", new { area = "PainelAdministrativo"});
                //TODO: Implementar sistema de controle de acesso em páginas específicas
            }
            else
            {
                ViewBag.Error = true;
                ViewBag.UltimoEmail = Email;
                ViewData["Title"] = "Login";
                
                return View();
            }
        }   
    }
}

Cotacoes.MVC/Areas/Usuarios/Controllers/CadastroController.cs
using Cotacoes.Model;
using Microsoft.AspNetCore.Mvc;

namespace Cotacoes.MVC.Areas.Usuarios.Controllers
{
    [Area("Usuarios")]
    public class CadastroController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "Cadastro usuário";

            return View();
        }

        [HttpPost]
        public IActionResult Index([FromForm]string Nome, [FromForm]string Email, [FromForm]string Senha)
        {
            try
            {
                ViewData["Title"] = "Cadastro usuário";

                Usuario _usuario = new Usuario();

                _usuario.Nome = Nome;
                _usuario.Email = Email;
                _usuario.Senha = Senha;

                UsuarioService.Cadastrar(_usuario);

                ViewBag.UltimoEmail = Email;

                return RedirectToAction("Index","Autenticacao");
            }
            catch (System.Exception e)
            {
                ViewData["Title"] = "Cadastro usuário";
                ViewBag.Error = true;
                ViewBag.MensageErro = e.Message;

                return View();
            }
        }
    }
}

Cotacoes.MVC/Areas/Usuarios/Controllers/InformacoesController.cs
using Cotacoes.Model;
using Microsoft.AspNetCore.Mvc;

namespace Cotacoes.MVC.Areas.Usuarios.Controllers
{
    [Area("Usuarios")]
    public class InformacoesController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "Informações usuário";
            return View();
        }

        [HttpPut]
        public IActionResult Editar()
        {
            ViewData["Title"] = "Editar usuário";
            return View();
        }

        [HttpDelete]
        public IActionResult Delete(string email)
        {
            UsuarioService.Deletar(email);

            return View();
        }
    }
}

Cotacoes.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cotacoes.MVC.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return RedirectToAction("Index", "Cotacao", new { area = "Moedas" });
        }
    }
}

Cotacoes.MVC/Areas/Moedas/Views/Conversao/Index.cshtml
@page

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="padding-top:50px">
  <div class="panel panel-default">
  <div class="panel-heading"><h4>Converção de moeda</h4></div>
  <div class="panel-body">
    <form id="FormCotacoes" class="form-horizontal" method="post" action="">
    <fieldset>
    <!-- Prepended text-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="Moeda">Moeda</label>
      <div class="col-md-4">
        <div class="input-group">
          <span class="input-group-addon">Sigla</span>
          <input id="Moeda" name="Moeda" class="form-control" placeholder="BRL" type="text" required="">
        </div>
      </div>
    </div>

    <!-- Prepended text-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="Montante">Montante</label>
      <div class="col-md-4">
        <div class="input-group">
          <span class="input-group-addon">valor</span>
          <input id="Montante" name="Montante" class="form-control" placeholder="10,0" type="text" required="">
        </div>
      </div>
    </div>

  <!-- Multiple Radios -->
  <div class="form-group">
    <label class="col-md-4 control-label" for="Moeda">Converter para</label>
    <div class="col-md-4">
    <div class="radio">
      <label for="Moeda-0">
        <input type="radio" name="Moeda" id="Moeda-0" value="dolar" checked="checked">
        Dolar
      </label>
    </div>
    <div class="radio">
      <label for="Moeda-1">
        <input type="radio" name="Moeda" id="Moeda-1" value="real">
        Real
      </label>
    </div>
    </div>
  </div>

  <!-- Button -->
  <div class="form-group">
    <label class="col-md-4 control-label" for="Btn_Converter"></label>
    <div class="col-md-4">
      <button id="Btn_Converter" name="Btn_Converter" class="btn btn-primary btn-info" onclick="setAction()">
        <span class="glyphicon glyphicon-sort"></span> Converter</button>
    </div>
  </div>
  </fieldset>
    @{
      if(@ViewBag.Valor != -1 && @ViewBag.Valor != null)
      {
        <div class="alert alert-success" role="alert">
          <span class="glyphicon glyphicon-usd" aria-hidden="true"></span>
          Valor: @ViewBag.Valor
        </div>
      }
      else if(@ViewBag.Valor == -1)
      {
          <div class="alert alert-warning" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            Erro ao converter, verifique a siga da moeda e montante!
          </div>
      }
    }
  </form>
  </div>
</div>
</div>

<script>
  function setAction(){
    var statusRadio = document.getElementById("Moeda-0").checked == true;

    if(statusRadio){
      document.getElementById("FormCotacoes").action ="Conversao/ConverterParaDolar/";
    }
    else{
     document.getElementById("FormCotacoes").action = "Conversao/ConverterParaReal/";
    }
  }
</script>

Cotacoes.MVC/Areas/Moedas/Views/Informacoes/Index.cshtml
@page

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container" style="padding-top:50px;">
  <div class="table table-striped table-hover">
  <table class="table">
    <tr>
      <th style="text-align:center">Codigo</th>
      <th style="text-align:center">Sigla</th>
      <th style="text-align:center">Nome</th>
      <th style="text-align:center">Tipo</th>
    </tr>

    @{
      var listagem = Cotacoes.Model.MoedaService.Listar();

      foreach(var item in @listagem)
      {
        <tr style="text-align:center">
          <td>@Html.ActionLink(@item.Codigo.ToString(), "Sobre", "Informacoes", new { id = @item.Codigo }, null)</td>
          <td>@item.Sigla</td>
          <td>@item.Nome</td>
          <td>@item.Tipo</td>
        </tr>
      }
    }
  </table>
  </div>
</div>

Cotacoes.MVC/Areas/Moedas/Views/Informacoes/Sobre.cshtml
@page

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container" style="padding-top:50px;">
  <div class="panel panel-default">
    <div class="panel-heading"><h4>Informações</h4></div>
    <div class="panel-body">
      <ul class="list-group">
        <li class="list-group-item"><strong>Código:</strong> @ViewBag.Moeda.Codigo</li>
        <li class="list-group-item"><strong>Sigla:</strong> @ViewBag.Moeda.Sigla</li>
        <li class="list-group-item"><strong>Tipo:</strong> @ViewBag.Moeda.Tipo</li>
        <li class="list-group-item"><strong>Nome:</strong> @ViewBag.Moeda.Nome</li>
        <li class="list-group-item"><strong>Cód. País:</strong> @ViewBag.Moeda.CodigoPais</li>
        <li class="list-group-item"><strong>País:</strong>@ViewBag.Moeda.NomePais</li>
      </ul>

      <h6>*Em breve relatórios e gráficos sobre a moeda @ViewBag.Moeda.Nome.</h6>
    </div>
  </div>
  <a href="../" class="btn btn-primary btn-info"><span class="glyphicon glyphicon-chevron-left"></span> Voltar</a> 
</div>

Cotacoes.MVC/Areas/PainelAdministrativo/Views/Home/Index.cshtml
@page
@using Cotacoes.Model

@{
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="table table-striped table-hover">
   <table class="table" id="lista">
      <tr>
         <th style="text-align:center">ID</th>
         <th style="text-align:center">Nome</th>
         <th style="text-align:center">Email</th>
         <th style="text-align:center">Administrador</th>
         <th style="text-align:center">Ações</th>
      </tr>
      @{
        var listaUsu = UsuarioService.Listar();
        foreach(var item in listaUsu)
        {
            <tr style="text-align:center">
                <td>@item.ID</td>
                <td>@item.Nome</td>
                <td>@item.Email</td>
                @if(@item.Administrador == false)
                {
                <td>Não</td>
                }
                else
                {
                <td>Sim</td>
                }
                <td>
                    <span class="label label-warning">@Html.ActionLink("Editar", "Action", "Controller", new { id = @item.ID }, new{@style="color:White"})</span> 
                    <span class="label label-danger">@Html.ActionLink("Deletar", "Action", "Controller", new { id = @item.ID },new{@style="color:White"})</span>
                </td>
            </tr>
        }
      }
   </table>
</div>

Cotacoes.MVC/Areas/Usuarios/Views/Autenticacao/Index.cshtml
@page

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
<link rel="stylesheet" href="~/css/styleLogin.css" />
</head>
<div class="container">
  <div class="wrapper">
    <form onload="UltimoEmail()" class="form-signin" action="Autenticacao" method="post">
      <center><img src="https://cdn2.iconfinder.com/data/icons/flat-icons-19/512/Coin.png" height="100px;"></center>
      <input id="Email" style="margin-top:25px" type="text" class="form-control" name="Email" placeholder="Email" value="@ViewBag.UltimoEmail" required="" autofocus="" />
      <input style="margin-top:10px" type="password" class="form-control" name="Senha" placeholder="Senha" required=""/>
      <div id="erro" class="alert alert-danger" style="margin-top:20px;display: none;">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <span class="glyphicon glyphicon-asterisk"></span><strong> Erro:</strong> login ou senha inválidos
      </div>

      <button style="margin-top:30px;margin-bottom:15px" class="btn btn-lg btn-primary btn-block" type="submit">Logar</button>
      <a style="text-decoration: none;" href=@Url.Action("Index","Cadastro") >Realizar cadastro</a>
    </form>
  </div>
</div>

@{

  if(@ViewBag.Error == true)
  {
    <script>
      var MensagemErro = document.getElementById("erro");
      MensagemErro.style.display = "block";
    </script>
  }
}

Cotacoes.MVC/Areas/Usuarios/Views/Cadastro/Index.cshtml
@page

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container" style="margin-top:50px;">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Cadastro de usuário</h4></div>
        <div class="panel-body">
            <div class="wrapper">
              <form class="form-horizontal" action="Cadastro/Index" method="POST">
                <fieldset>
                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="Nome">Nome</label>  
                  <div class="col-md-4">
                  <input id="Nome" name="Nome" type="text" placeholder="Seu nome" class="form-control input-md" required="">
                    
                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="Email">Email</label>  
                  <div class="col-md-4">
                  <input id="Email" name="Email" type="text" placeholder="Seu email" class="form-control input-md" required="">
                    
                  </div>
                </div>

                <!-- Password input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="Senha">Senha</label>
                  <div class="col-md-4">
                    <input id="Senha" name="Senha" type="password" placeholder="Senha" class="form-control input-md" required="">
                    
                  </div>
                </div>

                <!-- Password input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="SenhaRepetuda">Repita sua senha</label>
                  <div class="col-md-4">
                    <input id="SenhaRepetida" name="SenhaRepetida" type="password" placeholder="Repita sua senha" class="form-control input-md" onchange="validarSenha()" required="">
                    
                  </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="Cadastrar"></label>
                  <div class="col-md-4">
                    <button id="Cadastrar" name="Cadastrar" class="btn btn-info">Cadastrar novo usuário</button>
                  </div>
                </div>

                </fieldset>
                  <div id="erro" class="alert alert-danger" style="margin-top:20px;display: none;">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <span class="glyphicon glyphicon-asterisk"></span><strong> Erro:</strong> não foi possível cadastrar um novo usuário - @ViewBag.MensageErro
                  </div>
              </form>
            </div>
        </div>  
    </div>
</div>

<script>
  function validarSenha()
  { 
    if (document.getElementById("SenhaRepetida").value != document.getElementById("Senha").value)
    {
      input.setCustomValidity('Repita a senha corretamente');
      alert("Erro!");
    } 
    else 
    {
      input.setCustomValidity('');
    }
  } 
</script>

@{
  if(@ViewBag.Error == true)
  {
    <script>
      var MensagemErro = document.getElementById("erro");
      MensagemErro.style.display = "block";
    </script>
  }
}
    

Cotacoes.MVC/Areas/Usuarios/Views/Informacoes/Editar.cshtml
@page

@{
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container" style="margin-top:50px;">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Informações usuário</h4></div>
        <div class="panel-body">
            <div class="wrapper">
              <form class="form-horizontal" action="Cadastro/Index" method="POST">
                <fieldset>
                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="Nome">Nome</label>
                  <div class="col-md-4">
                  <input id="Nome" name="Nome" type="text" placeholder="Seu nome" class="form-control input-md" required="">
                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="Email">Email</label>
                  <div class="col-md-4">
                  <input id="Email" name="Email" type="text" placeholder="Seu email" class="form-control input-md" required="">
                  </div>
                </div>

                <!-- Password input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="Senha">Senha</label>
                  <div class="col-md-4">
                    <input id="Senha" name="Senha" type="password" placeholder="Senha" class="form-control input-md" required="">
                  </div>
                </div>

                <!-- Password input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="SenhaRepetuda">Repita sua senha</label>
                  <div class="col-md-4">
                    <input id="SenhaRepetida" name="SenhaRepetida" type="password" placeholder="Repita sua senha" class="form-control input-md" onchange="validarSenha()" required="">
                  </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="Cadastrar"></label>
                  <div class="col-md-4">
                    <button id="Cadastrar" name="Cadastrar" class="btn btn-info">Atualizar cadastro</button>
                  </div>
                </div>

                </fieldset>
                  <div id="erro" class="alert alert-danger" style="margin-top:20px;display: none;">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <span class="glyphicon glyphicon-asterisk"></span><strong> Erro:</strong> não foi possível cadastrar um novo usuário - @ViewBag.MensageErro
                  </div>
              </form>
            </div>
        </div>
    </div>
</div>

Cotacoes.MVC/Areas/Usuarios/Views/Informacoes/Index.cshtml
@page

@{
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div style="margin-top:30px;">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Informações usuário</h4></div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-2 col-md-offset-1">
                    <a asp-controller="Informacoes" asp-action="Editar" id="Editar" name="Editar" class="btn btn-info">Editar informações</a>
                </div>
                <div class="col-md-2">
                   <a asp-controller="Informacoes" asp-action="Excluir" id="Excluir" name="Excluir" class="btn btn-danger">Excluir contata</a>
                </div>
            </div>
        </div>
    </div>
</div>